### PR TITLE
Add variables for types of trucks

### PR DESCRIPTION
**Pull request by danielhuppmann**
Per email request by Nikolaos Tsanakas

### CODE REVIEW

**Comment by nikostsanakas** [comment]
Hi Daniel, 
Yes, that works for our use case. Thank you!  What about the two new variables?
Stock|Transportation|{Transport mode, tech and carrier}
Sales|Transportation|{Transport mode, tech and carrier}

**Comment by danielhuppmann** [comment]
Added the two variables as requested

**Comment by nikostsanakas** [comment]
Ok  thank you! Should I do anything else so that I can see these changes in the Open entrance main?

**Comment by danielhuppmann** [comment]
Do these changes meet your requirements?

**Comment by nikostsanakas** [comment]
Yes, they do

**Pull request merged**
