### PR TITLE
adding transportation investments and running costs

### PR DESCRIPTION
**Pull request by robertpietzcker**

### CODE REVIEW

**Comment by robertpietzcker** [comment]
@danielhuppmann I have to say I  don't understand the Nomenclature/validation error message. Any hints?

**Comment by phackstock** [comment]
@robertpietzcker, sorry for the inconvenience, see my answer here: https://github.com/openENTRANCE/openentrance/pull/326#issuecomment-1934666077

**Comment by danielhuppmann** [comment]
The error message will be fixed by merging #326

**Comment by danielhuppmann** [comment]
Closing and reopening to trigger the GitHub Actions workflows after fixing the nomenclature CLI issue

**Review by danielhuppmann — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
